kind: "Template"
apiVersion: "v1"
metadata:
    name: nf-e-hmg
    annotations:
      description: "nf-e-hmg"
      tags: "nginx"
objects:

  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: nfe-backend-nginx
      namespace: nf-e-hmg
    spec:
      lookupPolicy:
        local: false

  - apiVersion: build.openshift.io/v1
    kind: Build
    metadata:
      name: nfe-backend-nginx
      namespace: nf-e-hmg
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: 'nfe-backend-nginx:latest'
      revision:
        type: Git
      source:
        git:
          ref: master
          uri: 'https://github.com/culturagovbr/nfe'
        type: Git
      strategy:
        dockerStrategy:
          dockerfilePath: docker/nginx/Dockerfile
        type: Docker
      triggeredBy: null

  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: nfe-backend-nginx
      namespace: nf-e-hmg
    spec:
      replicas: 1
      revisionHistoryLimit: 2
      selector:
        name: nfe-backend-nginx
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            name: nfe-backend-nginx
        spec:
          containers:
            - image: nfe-backend-nginx
              imagePullPolicy: Always
              name: nfe-backend-nginx
              ports:
                - containerPort: 8081
                  protocol: TCP
                - containerPort: 8443
                  protocol: TCP
          dnsPolicy: ClusterFirst
          restartPolicy: Always
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - nfe-backend-nginx
            from:
              kind: ImageStreamTag
              name: 'nfe-backend-nginx:latest'
              namespace: nf-e-hmg
          type: ImageChange


  - apiVersion: v1
    kind: Service
    metadata:
      name: nfe-backend-nginx
      namespace: nf-e-hmg
    spec:
      ports:
        - port: 8443
          protocol: TCP
          targetPort: 8443
      selector:
        deploymentconfig: nfe-backend-nginx
      type: ClusterIP

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: nfe-backend-nginx
      name: nfe-backend-nginx
      namespace: nf-e-hmg
    spec:
      port:
        targetPort: 8443
      to:
        kind: Service
        name: nfe-backend-nginx
        weight: 100
      tls:
        termination: passthrough
      wildcardPolicy: None